export const GET_FILMS = "GET_FILMS";
export const GET_CHARACTERS = "GET_CHARACTERS";
export const FILTER_CHARACTERS_EYECOLOR = "FILTER_CHARACTERS_EYECOLOR";
export const FILTER_CHARACTERS_GENDER = "FILTER_CHARACTERS_GENDER";